In [12]:
import pandas as pd
import psycopg2
from bs4 import BeautifulSoup

def extract_text(html):
    return BeautifulSoup(html, 'html.parser').get_text()

# Apply function to column
conn = psycopg2.connect(
    host="ec2-3-230-24-12.compute-1.amazonaws.com",
    database="d6egi1sged4ei0",
    user="gxybdgkzxodngd",
    password="849b29123686ffba9dea3e30cd5b7fea68d1e659f6a3152e9d6b830c6188803c"
)

# Create a pandas dataframe from the SQL query results
sql_query = '''
SELECT * FROM pit_data
'''
df = pd.read_sql_query(sql_query, conn)
df

/tmp/ipykernel_11940/3926888725.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(sql_query, conn)

,id,team_number,team_name,data,created_at,created_by,updated_at,updated_by,available
0,63,1,W,{},2023-04-06 04:12:28.002990,E,2023-04-06 04:12:28.002990,E,True
1,64,1,2,{},2023-04-06 04:13:02.282510,3,2023-04-06 04:13:02.282510,3,True
2,65,2,W,{},2023-04-06 04:13:40.666821,2,2023-04-06 04:13:40.666821,2,True
3,66,1,W,{},2023-04-06 04:16:16.386227,3,2023-04-06 04:16:16.386227,3,True
4,67,1,1,{},2023-04-06 04:18:42.328413,2,2023-04-06 04:18:42.328413,2,True
5,68,1,2,{},2023-04-06 04:20:05.749380,3,2023-04-06 04:20:05.749380,3,True
6,69,1,1,{},2023-04-06 04:20:05.855618,1,2023-04-06 04:20:05.855618,1,True
7,70,1,1,{},2023-04-06 04:20:31.067022,1,2023-04-06 04:20:31.067022,1,True
8,71,1,1,{},2023-04-06 04:21:39.439185,1,2023-04-06 04:21:39.439185,1,True
9,72,1,1,{},2023-04-06 04:27:05.687088,1,2023-04-06 04:27:05.687088,1,True
10,73,1,1,{},2023-04-06 04:27:05.930071,1,2023-04-06 04:27:05.930071,1,True
11,74,1,1,{},2023-04-06 04:27:18.616417,1,2023-04-06 04:27:18.616417,1,True
12,75,1d3,d3,{},2023-04-06 04:28:46.745296,d3,2023-04-06 04:28:46.745296,d3,True
13,76,1dfr,ef,{},2023-04-06 04:32:46.902528,er,2023-04-06 04:32:46.902528,er,True
14,77,23d,d3,{},2023-04-06 04:32:47.007638,2d3,2023-04-06 04:32:47.007638,2d3,True
15,78,1,2,{},2023-04-06 04:36:07.032276,E,2023-04-06 04:36:07.032276,E,True
16,79,13,23,{},2023-04-06 04:40:05.553051,2e3,2023-04-06 04:40:05.553051,2e3,True
17,80,testonline,testonline,{},2023-04-06 04:41:16.573964,testonline,2023-04-06 04:41:16.573964,testonline,True
18,81,testLapt,testLapt,{},2023-04-06 04:45:19.381726,testLapt,2023-04-06 04:45:19.381726,testLapt,True
19,82,Kd,Ed,{},2023-04-06 04:51:21.508976,De,2023-04-06 04:51:21.508976,De,True
20,83,2357,Sistem meltdown,"{""field4"":{""number"":""0.01"",""currency"":""mt""},""f...",2023-04-06 16:18:50.862505,"Ely, Eloise, Sarahí",2023-04-06 16:18:50.862505,"Ely, Eloise, Sarahí",True
21,84,6026,Tiger strike,"{""field4"":{""number"":""10"",""currency"":""in""},""fie...",2023-04-06 16:30:21.129318,Ely Eloise sarahi,2023-04-06 16:30:21.129318,Ely Eloise sarahi,True
22,85,3163,Roarbots,"{""field4"":{""number"":""10"",""currency"":""in""},""fie...",2023-04-06 16:39:58.607072,Eloise,2023-04-06 16:39:58.607072,Eloise,True
23,86,2160,FROD,"{""field6"":12,""field7"":1,""field8"":1,""field9"":""S...",2023-04-06 16:57:14.974079,Ely Eloise Sarahí,2023-04-06 16:57:14.974079,Ely Eloise Sarahí,True
24,87,8086,RoboWarrios,"{""field11"":""2"",""field12"":""0"",""field14"":""0"",""fi...",2023-04-06 20:55:08.226843,Saris,2023-04-06 20:55:08.226843,Saris,True
25,88,2373,The Cricket,"{""field6"":7,""field7"":1,""field8"":1,""field9"":""Sw...",2023-04-06 21:00:23.121706,Ely,2023-04-06 21:00:23.121706,Ely,True
26,89,31,Prime Mobers,"{""field11"":""1"",""field12"":""1"",""field13"":1,""fiel...",2023-04-06 21:06:50.450701,Saris,2023-04-06 21:06:50.450701,Saris,True
27,90,2773,IRONDOGZ,"{""field6"":4,""field7"":1,""field8"":2,""field9"":""Tr...",2023-04-06 21:07:15.756093,Ely,2023-04-06 21:07:15.756093,Ely,True
28,91,1ew,we3,{},2023-04-06 21:08:46.791256,2e,2023-04-06 21:08:46.791256,2e,True
29,92,2083,Blitz,"{""field11"":""1"",""field12"":""1"",""field13"":2,""fiel...",2023-04-06 21:14:42.672139,Saris,2023-04-06 21:14:42.672139,Saris,True
30,93,2165,BISONBOTS,"{""field6"":8,""field8"":3,""field9"":""Swerve"",""fiel...",2023-04-06 21:19:29.917140,Ely,2023-04-06 21:19:29.917140,Ely,True
31,94,1209,Robohorneta,"{""field11"":""1"",""field12"":""1"",""field13"":1,""fiel...",2023-04-06 21:22:17.239389,Saris,2023-04-06 21:22:17.239389,Saris,True
32,98,6424,Barker Redbacks,"{""field6"":8,""field7"":3,""field8"":2,""field9"":""Sw...",2023-04-06 21:49:10.880652,Ely y Sarahí,2023-04-06 21:49:10.880652,Ely y Sarahí,True
33,95,1209,Robohorneta,"{""field11"":""1"",""field12"":""1"",""field13"":1,""fiel...",2023-04-06 21:22:17.438165,Saris,2023-04-06 21:22:17.438165,Saris,True
34,96,5006,Apophis,"{""field6"":8,""field7"":1,""field8"":2,""field9"":""Sw...",2023-04-06 21:29:40.313201,Ely,2023-04-06 21:29:40.313201,Ely,True
35,97,3465,Omega factor,"{""field11"":""1"",""field12"":""1"",""field13"":1,""fiel...",2023-04-06 21:30:05.092966,Saeis,2023-04-06 21:30:05.092966,Saeis,True
36,99,7483,Mechanically challenged,"{""field6"":6,""field7"":1,""field8"":1,""field9"":""We...",2023-04-06 22:04:12.952703,Ely,2023-04-06 22:04:12.952703,Ely,True
37,100,2359,Robo Lobos,"{""field6"":8,""field7"":2,""field8"":2,""field9"":""Sw...",2023-04-06 22:13:19.586582,Ely y Sarahí,2023-04-06 22:13:19.586582,Ely y Sarahí,True
38,101,2395,Ninja Munkees,"{""field6"":4,""field7"":2,""field8"":1,""field11"":""3...",2023-04-06 22:23:27.444163,Ely,2023-04-06 22:23:27.444163,Ely,True
39,102,3931,Coockadoodld,"{""field11"":""1"",""field12"":""0"",""field14"":""1"",""fi...",2023-04-06 22:24:23.781594,Saris,2023-04-06 22:24:23.781594,Saris,True
40,103,4005,Tiger Country,"{""field4"":{""number"":0,""currency"":""mt""},""field6...",2023-04-06 22:40:49.660341,Elise Wisdom,2023-04-06 22:40:49.660341,Elise Wisdom,True
41,104,6424,Stealth Panther Robotics,"{""field4"":{""number"":""53.5"",""currency"":""in""},""f...",2023-04-06 22:48:35.271748,Elise Wisdom,2023-04-06 22:48:35.271748,Elise Wisdom,True
42,105,4646,Wildcard Robotics,"{""field6"":4,""field7"":2,""field8"":4,""field9"":""Sw...",2023-04-06 22:53:33.876107,Ely,2023-04-06 22:53:33.876107,Ely,True
43,106,1750,Thunderstorm Robotics,"{""field4"":{""number"":""52"",""currency"":""in""},""fie...",2023-04-06 22:56:28.235689,Elise Wisdom,2023-04-06 22:56:28.235689,Elise Wisdom,True
44,107,2333,Creeh,"{""field11"":""1"",""field12"":""1"",""field13"":2,""fiel...",2023-04-06 22:57:06.941427,Saris,2023-04-06 22:57:06.941427,Saris,True
45,108,8711,The Midnight Ostrichs,"{""field11"":""2"",""field12"":""0"",""field13"":1,""fiel...",2023-04-06 23:02:48.113680,Saris,2023-04-06 23:02:48.113680,Saris,True
46,109,2972,Gears and Buccaneers,"{""field6"":4,""field8"":0,""field9"":""Swerve"",""fiel...",2023-04-06 23:04:30.338046,Ely,2023-04-06 23:04:30.338046,Ely,True
47,110,2352,Metal Mayhem,"{""field4"":{""number"":""53.5"",""currency"":""in""},""f...",2023-04-06 23:05:31.704102,Elise Wisdom,2023-04-06 23:05:31.704102,Elise Wisdom,True
48,111,3507,UBOTICS,"{""field11"":""1"",""field12"":""1"",""field13"":2,""fiel...",2023-04-06 23:19:30.761971,Ely y Sarahi,2023-04-06 23:19:30.761971,Ely y Sarahi,True
49,112,1986,Team Titanium,"{""field11"":""2"",""field12"":""1"",""field13"":1,""fiel...",2023-04-06 23:27:31.782918,Ely,2023-04-06 23:27:31.782918,Ely,True
50,113,1339,Angelbotics,"{""field4"":{""number"":""44"",""currency"":""in""},""fie...",2023-04-06 23:35:50.564689,Ely y Sarahí,2023-04-06 23:35:50.564689,Ely y Sarahí,True
51,114,1,1,{},2023-04-07 00:56:15.727533,1,2023-04-07 00:56:15.727533,1,True
52,115,1,1,{},2023-04-07 02:00:50.418988,1,2023-04-07 02:00:50.418988,1,True
53,116,TestOnline,1,{},2023-04-07 02:33:55.567436,1,2023-04-07 02:33:55.567436,1,True
54,117,1,2,{},2023-04-07 02:45:27.862615,3,2023-04-07 02:45:27.862615,3,True
55,118,G,Jj,{},2023-04-07 02:46:57.888008,J,2023-04-07 02:46:57.888008,J,True
56,119,1,2,{},2023-04-07 13:38:35.257534,3,2023-04-07 13:38:35.257534,3,True
57,120,1,E,{},2023-04-07 13:38:37.490436,Y,2023-04-07 13:38:37.490436,Y,True
58,121,1,1,{},2023-04-07 13:38:38.287952,1,2023-04-07 13:38:38.287952,1,True
59,122,Rrf,Fgf,{},2023-04-07 15:36:41.713636,Gff,2023-04-07 15:36:41.713636,Gff,True

In [ ]:
df_normalized = pd.json_normalize(df['data'].apply(eval))

# Concatenate the normalized DataFrame with the original DataFrame
df = pd.concat([df, df_normalized], axis=1)
df.drop('data', axis=1, inplace=True)

In [ ]:
my_dict = {
    "field1": "TeamNum",
    "field2": "MatchNum",
    "field3": "Scouter",
    "field4": "Altura_del_robot",
    "field5": "Peso_del_robot",
    "field6": "#_de_motores_chasis",
    "field7": "#_de_motores_intake",
    "field8": "#_de_motores_elevador",
    "field9": "tipo_de_chasis",
    "field10": "tipo_de_wheels",
    "field11": "lenguaje",
    "field12": "vision",
    "field13": "camara",
    "field14": "sensores",
    "field15": "tipo_sensor",
    "field16": "auto",
    "field17": "mobility",
    "field18": "gp_auto",
    "field19": "nivel_auto",
    "field20": "charge_station",
    "field21": "gpick_auto",
    "field22": "donde_gp",
    "field23": "gp_nivel",
    "field24": "tipo_mecanismo_intake",
    "field25": "tipo_mecanismo_elevador",
    "field26": "balancea",
    "field27": "balanceo_auto",
    "field28": "gp_numero",
    "field29": "defensa",
    "field30": "prioridad",
}
df.rename(columns=my_dict, inplace=True)
df.to_csv('pit.csv', index=False)